# Generated by Django 3.1.7 on 2021-03-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazine', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='magazine.company', verbose_name='Компания работадатель'),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='jobs.position', verbose_name='Выбирите должность'),
        ),
        migrations.AddField(
            model_name='job',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_technology', to='jobs.technology', verbose_name='Выберите технологию'),
        ),
        migrations.AddField(
            model_name='job',
            name='type_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_time', to='jobs.typetime', verbose_name='Выберите время'),
        ),
    ]
