# Generated by Django 3.1.7 on 2021-03-14 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Названия')),
                ('slug', models.SlugField(unique=True, verbose_name='Ярлык')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('map', models.CharField(max_length=250, verbose_name='Карта')),
                ('site', models.URLField(verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('slug', models.SlugField(unique=True, verbose_name='Ярлык')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_city', to='events.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Место проведении',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.FileField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('date_start', models.DateTimeField(verbose_name='Начало')),
                ('date_end', models.DateTimeField(verbose_name='Конец')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Мероприятие на весь день')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платный?')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('is_premium_event', models.BooleanField(default=False, verbose_name='Премиум события?')),
                ('is_going', models.IntegerField(blank=True, null=True, verbose_name='Не иду/Иду')),
                ('site', models.URLField(verbose_name='Сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('slug', models.SlugField(unique=True, verbose_name='Ярлык')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('bookmark', models.ManyToManyField(blank=True, related_name='user_bookmark_event', to=settings.AUTH_USER_MODEL, verbose_name='В избранных')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
                'db_table': 'event',
            },
        ),
    ]
